import { ChapterType } from './types/chapterType';

export const newChapters = [
  {
    id: 1,
    name: 'The Amazing Spider-Man (2022) #34',
  },
  {
    id: 2,
    name: 'The Amazing Spider-Man (2022) #35',
  },
  {
    id: 3,
    name: 'The Amazing Spider-Man (2022) #36',
  }
];

export const pagesList = [
  {
    chapterId: 1,
    pages: [
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/01.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/02.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/03.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/04.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/05.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/06.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/07.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/08.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/09.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/10.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/11.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/12.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/13.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/14.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/15.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/16.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/17.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/18.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/19.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/20.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/21.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/22.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/23.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/24.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/25.jpg',
    ],
  },
  {
    chapterId: 2,
    pages: [
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/01.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/02.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/03.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/04.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/05.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/06.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/07.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/08.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/09.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/10.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/11.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/12.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/13.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/14.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/15.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/16.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/17.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/18.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/19.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/20.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/21.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/22.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/23.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/24.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/25.jpeg',
    ],
  },
  {
    chapterId: 3,
    pages: [
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/01.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/02.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/03.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/04.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/05.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/06.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/07.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/08.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/09.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/10.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/11.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/12.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/13.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/14.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/15.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/16.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/17.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/18.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/19.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/20.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/21.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/22.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/23.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/24.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/25.jpg',
    ],
  },
]

const chapters = [
  {
    id: 1,
    name: 'Amazing spider-man #34',
    pages: [
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/01.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/02.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/03.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/04.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/05.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/06.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/07.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/08.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/09.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/10.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/11.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/12.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/13.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/14.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/15.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/16.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/17.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/18.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/19.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/20.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/21.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/22.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/23.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/24.jpg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/34/25.jpg',
    ],
  },
  {
    id: 2,
    name: 'Amazing spider-man #35',
    pages: [
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/01.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/02.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/03.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/04.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/05.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/06.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/07.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/08.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/09.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/10.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/11.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/12.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/13.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/14.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/15.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/16.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/17.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/18.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/19.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/20.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/21.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/22.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/23.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/24.jpeg',
      'https://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2022/chapters/35/25.jpeg',
    ],
  },
] as ChapterType[];

export default chapters;